apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
- frontend.yaml
- infrastructure.yaml
  
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: github }]
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 60
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=booking-microservices
images:
- name: ghcr.io/ebz-adriannikiel/course-bm-booking
  newTag: 1.1.6
- name: ghcr.io/ebz-adriannikiel/course-bm-flight
  newTag: 1.1.6
- name: ghcr.io/ebz-adriannikiel/course-bm-identity
  newTag: 1.1.6
- name: ghcr.io/ebz-adriannikiel/course-bm-passenger
  newTag: 1.1.6
